'''
    Description
    -----------
    Tool for making requests related to travel time calculations.
    Receives data generated by TARS to perform calculations related to the user's queried trip.


'''

# Import the 'calc' module from the 'astro_calc' library and the 'sys' module for handling command-line arguments.
from astro_calc.calc import *
import sys

# Try to retrieve command-line arguments.
try:
    # The first argument (index 0) is typically the script name, so we start with the second argument (index 1).
    p1 = sys.argv[1]  # Origin planet
    p2 = sys.argv[2]  # Destination planet
    rocket = sys.argv[3]  # Type of rocket used

    # Try to retrieve a fourth argument, which is optional and represents the date of the journey.
    try:
        date = sys.argv[4]
    except IndexError:
        date = None

    # Call the 'calc' function with the provided arguments and the date (which can be None).
    result = calc(p1, p2, rocket, date)

    # Print the result of the calculations.
    print(result)

# Catch an exception if not enough arguments are provided.
except IndexError:
    print("You must mention the date, origin planet, destination planet, and the type of rocket for the journey")




